stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: svelte-app
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA

# Cache node modules to speed up builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - svelte/node_modules/

test:
  stage: test
  image: node:20-alpine
  script:
    - cd svelte
    - yarn install --frozen-lockfile
    # Make sure adapter-static is installed
    - yarn add -D @sveltejs/adapter-static
    - yarn check
    - yarn test
  only:
    - main
    - merge_requests

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG -t $DOCKER_IMAGE:latest -f Dockerfile .
    - docker save $DOCKER_IMAGE:$DOCKER_TAG | gzip > image.tar.gz
  artifacts:
    paths:
      - image.tar.gz
    expire_in: 1 week
  only:
    - main

deploy:
  stage: deploy
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker load < image.tar.gz
    # Stop any running container with the same name
    - docker stop $DOCKER_IMAGE || true
    - docker rm $DOCKER_IMAGE || true
    # Run the new container
    - docker run -d --name $DOCKER_IMAGE -p 8080:80 $DOCKER_IMAGE:$DOCKER_TAG
    - echo "Application deployed to http://localhost:8080"
  only:
    - main
  environment:
    name: production
    url: http://$CI_SERVER_HOST:8080
