name: Docker Build

on:
  push:
    branches:
      - main  # Change this to your target branch
  pull_request:
    branches:
      - main  # Change this to your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: code
          file: code/Dockerfile
          platforms: linux/amd64
          push: false
          tags: mathisve/go-sample-app