name: Deploy Vue Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master
        #with:
        #  path: 'vue/'

      - name: Build Docker Image 🐳
        run: docker build . -t vue-app:latest

  deploy:
    runs-on: self-hosted
    steps:
      - name: Remove exist container 🏺
        run: docker rm -f backend

      - name: Ensure Docker Network Created 🌐
        run: |
          if ! sudo docker network inspect backend > /dev/null 2>&1; then
            sudo docker network create backend
          fi

      - name: Run Docker Container 🏺
        run: docker run -p 8085:8080 --network backend --name backend -d vue-app:latest
