name: deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Build Docker Image 🐳
        run: sudo docker build -f Dockerfile . -t php-dev:latest

      - name: Remove exist container 🏺
        run: sudo docker rm -f php-dev:latest

      - name: Run Docker Container 🏺
        run: sudo docker run -p 80 --network backend --name php-dev -d php-dev:latest
