# do-sample-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: do-sample-app
spec:
  replicas: 3 # Adjust the replica count as needed
  selector:
    matchLabels:
      app: do-sample-app
  template:
    metadata:
      labels:
        app: do-sample-app
    spec:
      containers:
      - name: do-sample-app
        image: mathisve/do-sample-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 128Mi
            cpu: 64m
        envFrom:
        - secretRef:
            name: pg-connection
---
apiVersion: v1
kind: Service
metadata:
  name: do-sample-app-service
spec:
  selector:
    app: do-sample-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP