name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check Django Project
      run: |
        python manage.py check
        python manage.py makemigrations --check --dry-run
        
  deploy:
    runs-on: self-hosted
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker Image
      run: |
        docker build -t django-app:latest .
        
    - name: Stop existing container
      run: |
        docker rm -f django-app || true
        
    - name: Ensure Docker Network Created
      run: |
        if ! docker network inspect backend > /dev/null 2>&1; then
          docker network create backend
        fi
        
    - name: Start container
      run: |
        docker run -d \
          --name django-app \
          --network backend \
          -p 8000:8000 \
          -e DJANGO_VERSION=Production \
          -e DEBUG=False \
          --restart always \
          django-app:latest
