---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: do-api-token
type: Opaque
data:
  token: <YOUR_BASE64_ENCODED_DO_API_TOKEN_HERE>

---
apiVersion: do.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: do-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: do-api-token
      key: token
