apiVersion: v1
kind: Pod
metadata:
  name: curl-test
spec:
  containers:
    - name: curl
      image: curlimages/curl:7.80.0
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
