name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Build Docker Image 🐳
        run: sudo docker build -f Dockerfile . -t python-app:latest

  deploy:
    runs-on: self-hosted
    steps:
      - name: Remove exist container 🏺
        run: sudo docker rm -f python-app

      - name: Ensure Docker Network Created 🌐
        run: |
          if ! sudo docker network inspect backend > /dev/null 2>&1; then
            sudo docker network create backend
          fi

      - name: Run Docker Container 🏺
        run: sudo docker run -p 8083:80 --network backend --name python-app -d python-app:latest
