name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Build Docker Image 🐳
        run: sudo docker build -f Dockerfile . -t python-app:latest

      - name: Remove exist container 🏺
        run: sudo docker rm -f app1

      - name: Ensure Docker Network Created 🌐
        run: |
          if ! sudo docker network inspect backend > /dev/null 2>&1; then
            sudo docker network create backend
          fi

      - name: Run Docker Container 🏺
        run: sudo docker run -p 8082 --network backend --name app1 -d python-app:latest
