name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build image for scanning
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: docker-registry-demo:test
          outputs: type=docker,dest=/tmp/test-image.tar
      
      - name: Upload image as artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: docker-image
          path: /tmp/test-image.tar
          retention-days: 1

  test-and-scan:
    needs: prepare-image
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4.1.9
        with:
          name: docker-image
          path: /tmp
      
      - name: List files for debugging
        run: ls -la /tmp
      
      - name: Load Docker image
        run: docker load --input /tmp/test-image.tar
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker-registry-demo:test
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  build-and-push:
    needs: test-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/docker-registry-demo:latest
            ghcr.io/${{ github.repository_owner }}/docker-registry-demo:${{ github.sha }}
