apiVersion: v1
kind: Service
metadata:
  name: my-k8s-app # ชื่อ Service
spec:
  selector:
    app: my-k8s-app # เลือก Pod ที่มี label นี้
  ports:
  - port: 80       # พอร์ต Service ที่ expose
    targetPort: 3000 # พอร์ตที่ container ใช้งาน
  type: ClusterIP  # ประเภทของ Service
