name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        working-directory: react-app
        run: npm install

      - name: Run tests
        working-directory: react-app
        run: npm test -- --watchAll=false

      - name: Build React app
        working-directory: react-app
        run: npm run build

      - name: Build Docker image
        run: docker build -f Dockerfile -t my-react-app:latest .
      
      - name: Ensure Docker Network Created 🌐
        run: |
          if ! sudo docker network inspect backend > /dev/null 2>&1; then
            sudo docker network create backend
          fi

      - name: Run Docker container 🏃
        run: sudo docker run -d -p 3000:80 --name react --network backend my-react-app:latest
