version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: password
      POSTGRES_DB: racksync
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app2-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: example@racksync.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8082:80"
    depends_on:
      - postgres
    networks:
      - app2-network

networks:
  app2-network:
    driver: bridge

volumes:
  pg_data:
